'use client';
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { RsvpFields,formPayload,type Draft } from '@/components/rsvp-fields';
import { statistics,type RsvpRecord } from '@/lib/rsvp-domain';
import { coupleNames } from '@/lib/wedding-config';
const statusLabels={pending:'待联系',confirmed:'已确认',none:'无需安排'};
export default function AdminDashboard(){const [records,setRecords]=useState<RsvpRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[stay,setStay]=useState('all'),[date,setDate]=useState(''),[editing,setEditing]=useState<RsvpRecord|null>(null),[draft,setDraft]=useState<Draft|null>(null),[status,setStatus]=useState('none'),[busy,setBusy]=useState(false),[confirmDelete,setConfirmDelete]=useState<string|null>(null);
  async function reload(){setLoading(true);setError('');try{const r=await fetch('/api/admin/rsvps',{cache:'no-store'}),data=await r.json() as {error:string;record:RsvpRecord;records:RsvpRecord[]};if(!r.ok)throw new Error(data.error);setRecords(data.records);}catch(e){setError(e instanceof Error?e.message:'加载失败，请重试。');}finally{setLoading(false);}}
  useEffect(()=>{void reload();},[]);
  const stats=statistics(records),filtered=records.filter(r=>(!search||r.name.includes(search)||r.phone.includes(search))&&(stay==='all'||r.needsStay===(stay==='yes'))&&(!date||r.checkIn===date));
  function edit(r:RsvpRecord){setEditing(r);setDraft({...r,guests:String(r.guests),stayGuests:String(r.stayGuests||1),checkIn:r.checkIn||'',checkOut:r.checkOut||''});setStatus(r.status);setError('');}
  async function save(e:React.FormEvent){e.preventDefault();if(!editing||!draft||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/admin/rsvps/'+editing.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...formPayload(draft,e.currentTarget as HTMLFormElement),consent:true,status:draft.needsStay?(status==='none'?'pending':status):'none'})}),data=await r.json() as {error:string;record:RsvpRecord;records:RsvpRecord[]};if(!r.ok)throw new Error(data.error);setEditing(null);await reload();}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
  async function remove(id:string){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/admin/rsvps/'+id,{method:'DELETE'});if(!r.ok){const d=await r.json() as {error:string;record:RsvpRecord;records:RsvpRecord[]};throw new Error(d.error);}setConfirmDelete(null);await reload();}catch(e){setError(e instanceof Error?e.message:'删除失败');}finally{setBusy(false);}}
  return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">LETTERS FROM OUR FRIENDS</p><h1>婚礼回信管理</h1><p className="muted">{coupleNames} · 名单仅管理人员可见</p></div><a href="/">查看邀请函 ↗</a></header><div className="stat-grid">{[['报名组数',stats.groups],['出席人数',stats.guests],['住宿人数',stats.stayGuests],['住宿人晚',stats.nights]].map(([label,n])=><div key={label}><span>{label}</span><strong>{n}</strong></div>)}</div>
    <div className="admin-toolbar"><label>搜索姓名或电话<Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索宾客"/></label><label>住宿需求<select value={stay} onChange={e=>setStay(e.target.value)}><option value="all">全部宾客</option><option value="yes">需要住宿</option><option value="no">无需住宿</option></select></label><label>入住日期<Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><Button variant="outline" onClick={()=>{setSearch('');setStay('all');setDate('');}}>清除筛选</Button><Button variant="outline" onClick={reload} disabled={loading}>刷新</Button><a className="primary-link" href="/api/admin/export">导出全部 CSV</a></div>
    {error&&<p role="alert" className="form-error">{error}</p>}{loading?<p role="status">正在读取回信…</p>:<><p className="muted">显示 {filtered.length} / {records.length} 份回执 · 导出包含全部回执</p><Table><TableHeader><TableRow>{['宾客','联系电话','出席','住宿','日期','状态','操作'].map(s=><TableHead key={s}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(r=><TableRow key={r.id}><TableCell>{r.name}</TableCell><TableCell>{r.phone}</TableCell><TableCell>{r.guests}人</TableCell><TableCell>{r.needsStay?`${r.stayGuests}人`:'无需'}</TableCell><TableCell>{r.checkIn?<>{r.checkIn}<br/>{r.checkOut}</>:'—'}</TableCell><TableCell>{statusLabels[r.status]}</TableCell><TableCell><Button variant="ghost" onClick={()=>edit(r)}>查看 / 修改</Button>{confirmDelete===r.id?<><span>确定删除？不可恢复。</span><Button variant="destructive" disabled={busy} onClick={()=>remove(r.id)}>确认删除</Button><Button variant="ghost" onClick={()=>setConfirmDelete(null)}>取消</Button></>:<Button variant="ghost" onClick={()=>setConfirmDelete(r.id)}>删除</Button>}</TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<div className="admin-empty">{records.length?'没有符合筛选条件的回执。':'还没有收到回信。宾客提交后会出现在这里。'}</div>}</>}
    {editing&&draft&&<section className="admin-edit" aria-label="修改宾客回执"><form onSubmit={save}><div className="form-top"><h2>修改 · {editing.name}</h2><Button type="button" variant="ghost" onClick={()=>setEditing(null)}>关闭</Button></div><RsvpFields value={draft} onChange={setDraft} disabled={busy}/><label>住宿安排状态<select value={draft.needsStay?(status==='none'?'pending':status):'none'} onChange={e=>setStatus(e.target.value)} disabled={busy}>{draft.needsStay?<><option value="pending">待联系</option><option value="confirmed">已确认</option></>:<option value="none">无需安排</option>}</select></label>{error&&<p className="form-error" role="alert">{error}</p>}<Button className="submit-button" type="submit" disabled={busy}>{busy?'正在保存…':'保存修改'}</Button></form></section>}
    <footer className="admin-footer">联系方式与导出文件请妥善保管。婚礼结束后可导出备份，再按需清理记录。</footer>
  </main>;
}
