'use client';
import { useEffect,useRef,useState } from 'react';
import { ArrowDown,Copy,Music2,VolumeX } from 'lucide-react';
import { wedding } from '@/lib/wedding-config';
import { dayMessage } from '@/lib/rsvp-domain';
import { Button } from '@/components/ui/button';
export function OpenLetter(){const [opened,setOpened]=useState(false);return <a href="#letter" className="primary-link" onClick={()=>{setOpened(true);window.dispatchEvent(new Event('wedding-music-start'));document.getElementById('letter')?.classList.add('letter-open');}}>{opened?'邀请已开启':'打开这封邀请'}<ArrowDown size={16}/></a>;}
export function Countdown(){const [text,setText]=useState('期待与你相聚');useEffect(()=>{const update=()=>setText(dayMessage(wedding.date));update();const id=setInterval(update,60000);return()=>clearInterval(id);},[]);return <p className="countdown" aria-live="polite">✧ <span>{text}</span> ✧</p>;}
export function CopyAddress(){const [message,setMessage]=useState('');return <><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(`${wedding.venue.name} · ${wedding.venue.address}`);setMessage('地址已复制');}catch{setMessage('无法自动复制，请长按上方地址复制。');}}}><Copy size={14}/>复制地址</Button><span className="copy-message" role="status">{message}</span></>;}
export function Motion(){useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));return()=>observer.disconnect();},[]);return null;}
export function SparkleTrail(){const canvasRef=useRef<HTMLCanvasElement|null>(null);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;type Particle={x:number;y:number;vx:number;vy:number;life:number;size:number;hue:number};let particles:Particle[]=[],frame=0,lastX=-100,lastY=-100;const resize=()=>{const dpr=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0);};const add=(x:number,y:number,count=2)=>{for(let i=0;i<count;i++)particles.push({x:x+(Math.random()-.5)*10,y:y+(Math.random()-.5)*10,vx:(Math.random()-.5)*.7,vy:-.25-Math.random()*.65,life:1,size:1.5+Math.random()*3,hue:195+Math.random()*25});if(particles.length>240)particles.splice(0,particles.length-240);};const move=(e:PointerEvent)=>{if(Math.hypot(e.clientX-lastX,e.clientY-lastY)<6)return;lastX=e.clientX;lastY=e.clientY;add(e.clientX,e.clientY,e.pointerType==='touch'?4:3);};const down=(e:PointerEvent)=>add(e.clientX,e.clientY,12);const draw=()=>{ctx.clearRect(0,0,innerWidth,innerHeight);particles=particles.filter(p=>p.life>0);for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.life-=.012;const a=Math.max(0,p.life);ctx.save();ctx.translate(p.x,p.y);ctx.rotate((1-a)*1.5);ctx.globalAlpha=a*.9;ctx.fillStyle=`hsl(${p.hue} 85% 82%)`;ctx.shadowColor=`hsl(${p.hue} 95% 75%)`;ctx.shadowBlur=10;ctx.beginPath();for(let i=0;i<8;i++){const r=i%2?p.size*.25:p.size;const angle=i*Math.PI/4;const px=Math.cos(angle)*r,py=Math.sin(angle)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();ctx.fill();ctx.restore();}frame=requestAnimationFrame(draw);};resize();draw();addEventListener('resize',resize);addEventListener('pointermove',move,{passive:true});addEventListener('pointerdown',down,{passive:true});return()=>{cancelAnimationFrame(frame);removeEventListener('resize',resize);removeEventListener('pointermove',move);removeEventListener('pointerdown',down);};},[]);return <canvas ref={canvasRef} className="sparkle-trail" aria-hidden="true"/>;}
export function MusicToggle(){const audio=useRef<HTMLAudioElement|null>(null),[playing,setPlaying]=useState(false),[error,setError]=useState('');useEffect(()=>{if(audio.current)audio.current.volume=Math.min(1,Math.max(0,wedding.music.volume));const start=()=>{audio.current?.play().catch(()=>setError('点击音乐按钮即可播放'));};window.addEventListener('wedding-music-start',start);if(wedding.music.startOnFirstInteraction)document.addEventListener('pointerdown',start,{once:true,capture:true});return()=>{window.removeEventListener('wedding-music-start',start);document.removeEventListener('pointerdown',start,{capture:true});};},[]);if(!wedding.music.enabled||!wedding.music.src)return null;return <div className="music-control"><div className="music-caption"><span>{playing?'NOW PLAYING':'PLAY THE THEME'}</span><b>{wedding.music.title}</b><small>{wedding.music.artist}</small></div><audio ref={audio} src={wedding.music.src} preload="metadata" loop playsInline onPause={()=>setPlaying(false)} onPlay={()=>setPlaying(true)} onError={()=>{setPlaying(false);setError('音乐暂不可用，请稍后重试');}}/><Button variant="outline" size="icon" aria-label={playing?'暂停背景音乐':'播放背景音乐'} aria-pressed={playing} onClick={async()=>{setError('');if(playing){audio.current?.pause();return;}try{await audio.current?.play();}catch{setError('请再次点击播放音乐');}}}>{playing?<VolumeX/>:<Music2/>}</Button>{error&&<small className="music-error" role="status">{error}</small>}</div>;}
