'use client';
import { useEffect,useRef,useState } from 'react';
import { Send,Check,MailCheck,ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { RsvpFields,emptyDraft,formPayload,type Draft } from './rsvp-fields';
import { wedding } from '@/lib/wedding-config';
import { rsvpOpen,type RsvpRecord } from '@/lib/rsvp-domain';
const storageKey='frieren-wedding-receipt-v1';
function toDraft(r:RsvpRecord):Draft{return {...r,guests:String(r.guests),stayGuests:String(r.stayGuests||1),checkIn:r.checkIn||'',checkOut:r.checkOut||''};}
export default function RsvpForm(){
  const [draft,setDraft]=useState<Draft>(emptyDraft),[consent,setConsent]=useState(false),[record,setRecord]=useState<RsvpRecord|null>(null),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[storageWarning,setStorageWarning]=useState(false),[open,setOpen]=useState(wedding.rsvp.enabled);
  const token=useRef(''),lock=useRef(false),honeypot=useRef<HTMLInputElement>(null);
  useEffect(()=>{setOpen(rsvpOpen(wedding.rsvp));try{token.current=localStorage.getItem(storageKey)||'';}catch{setStorageWarning(true);}if(!token.current){setLoading(false);return;}fetch('/api/rsvp',{headers:{Authorization:`Bearer ${token.current}`},cache:'no-store'}).then(async r=>{const data=await r.json() as {error:string;record:RsvpRecord;records:RsvpRecord[]};if(r.ok){setRecord(data.record);setDraft(toDraft(data.record));}else if(r.status!==404)setError(data.error||'无法恢复回执，请稍后刷新；不要重复登记。');}).catch(()=>setError('暂时无法恢复回执，请检查网络后刷新。')).finally(()=>setLoading(false));},[]);
  async function submit(e:React.FormEvent){e.preventDefault();if(lock.current)return;setError('');if(draft.needsStay===null){setError('请选择是否需要住宿。');return;}if(!consent){setError('请先确认信息使用说明。');return;}lock.current=true;setBusy(true);
    try{if(!token.current){token.current=Array.from(crypto.getRandomValues(new Uint8Array(32))).map(n=>n.toString(16).padStart(2,'0')).join('');try{localStorage.setItem(storageKey,token.current);}catch{setStorageWarning(true);}}
      const response=await fetch('/api/rsvp',{method:record?'PATCH':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token.current}`},body:JSON.stringify({...formPayload(draft,e.currentTarget as HTMLFormElement),consent,website:honeypot.current?.value||''})});const data=await response.json() as {error:string;record:RsvpRecord};if(!response.ok)throw new Error(data.error||'保存失败，请稍后重试。');setRecord(data.record);setDraft(toDraft(data.record));setEditing(false);setConsent(false);
    }catch(e){setError(e instanceof Error?e.message:'网络异常，请稍后重试。');}finally{lock.current=false;setBusy(false);}
  }
  if(loading)return <div className="form-paper"><p role="status" className="muted">正在查看你的回信…</p></div>;
  if(record&&!editing)return <div className="form-paper success-panel" aria-live="polite"><MailCheck size={34}/><p className="eyebrow">YOUR LETTER HAS ARRIVED</p><h3>已收到你的回信</h3><p>期待与你在{wedding.venue.name}相见。</p><div className="receipt-summary"><span>{record.name}</span><span>{record.guests} 位旅伴赴约</span>{record.needsStay&&<span>住宿需求：{record.stayGuests} 人 · {record.checkIn} 至 {record.checkOut}</span>}</div>{record.needsStay&&<p className="muted">住宿需求已登记，具体安排将由新人后续联系确认。</p>}<p className="muted">本设备保留了修改凭证，请勿分享凭证。更换设备后可联系新人协助修改。</p>{storageWarning&&<p role="status" className="notice">当前浏览器无法保存修改凭证，关闭页面后请联系新人修改。</p>}{open?<Button onClick={()=>setEditing(true)} variant="outline">修改这份回执 <ArrowRight size={14}/></Button>:<p className="muted">登记已结束，需要修改请联系新人。</p>}</div>;
  if(!open)return <div className="form-paper"><h3>回信登记已结束</h3><p className="muted">如需补充或修改安排，请联系新人。期待与你相聚。</p></div>;
  return <form className="form-paper" onSubmit={submit} aria-label="宾客回执"><div className="form-top"><Send size={22}/><div><h3>{editing?'修改你的回信':'亲爱的旅伴，你会来吗？'}</h3><p className="muted">留下一点信息，让我们好好准备这次相聚。</p></div></div><RsvpFields value={draft} onChange={setDraft} disabled={busy}/><div className="honeypot" aria-hidden="true"><label>Website<input ref={honeypot} name="website" tabIndex={-1} autoComplete="off"/></label></div><div className="consent-row"><Checkbox id="privacy-consent" checked={consent} onCheckedChange={checked=>setConsent(checked===true)} disabled={busy}/><label htmlFor="privacy-consent">我确认以上信息仅用于本次婚礼联络与住宿安排，且仅管理人员可见。</label></div>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" className="submit-button" disabled={busy}>{busy?'正在寄出回信…':editing?'保存修改':'寄出我的回信'}{busy?null:<Check size={16}/>}</Button>{editing&&<Button type="button" variant="ghost" onClick={()=>{setDraft(toDraft(record!));setEditing(false);setError('');}}>取消修改</Button>}<p className="form-footnote">不采集证件信息 · 回信不会公开展示</p></form>;
}
