import { wedding as w, coupleNames, dateLabel,navigationUrl } from '@/lib/wedding-config';
import { ArrowDown, ArrowUpRight, Sparkles, MapPin,Compass, Camera,Flower2,Utensils,Leaf,ArrowUp,Clock3,Users,BedDouble } from 'lucide-react';
import { OpenLetter,Countdown,CopyAddress,Motion,MusicToggle,SparkleTrail } from '@/components/invitation-interactions';
import RsvpForm from '@/components/rsvp-form';
import WelcomeLetter from '@/components/welcome-letter';
export default function Home() {
  const date=new Date(w.date+'T12:00:00+08:00');
  const month=date.toLocaleDateString('en-US',{month:'long',timeZone:w.timezone}).toUpperCase();
  const weekday=date.toLocaleDateString('zh-CN',{weekday:'long',timeZone:w.timezone});
  const icons=[Compass,Flower2,Camera,Utensils];
  const events=w.events.filter(e=>e.enabled);
  return <main id="top">
    <Motion/><SparkleTrail/><WelcomeLetter/>
    <header className="site-header"><a href="#top" className="brand"><Sparkles size={19}/><span>旅 伴 来 信</span></a><span className="header-date">{dateLabel} · {w.venue.city}</span><a className="header-link" href="#details">婚礼邀请 <ArrowUpRight size={14}/></a></header>
    <section className="hero"><div className="hero-art"><img src={w.images.hero} alt="芙莉莲与辛美尔并肩走在蓝白花海与远方城镇之间" fetchPriority="high"/></div>
      <div className="hero-copy"><p className="eyebrow">A NEW CHAPTER, TOGETHER</p><p className="hero-prelude">致每一位，珍贵的旅伴</p><h1>{w.copy.headline.split('，').map(part=><span key={part}>{part.replace(/[，。！？、,.!?]/g,'')}</span>)}</h1><p className="hero-names">{w.couple.groom}<span>&</span>{w.couple.bride}</p><p className="hero-meta">{dateLabel} <span>✧</span> {w.venue.city} · {w.venue.name}</p><OpenLetter/><a className="quiet-link" href="#details">直接查看婚礼信息</a></div>
      <div className="hero-foot"><span>FRIEREN · A WEDDING JOURNEY</span><span>向下，开启我们的故事 <ArrowDown size={12}/></span></div>
    </section>
    <section className="letter section reveal" id="letter"><p className="eyebrow">01 / A LETTER TO YOU</p><h2>{w.copy.sections.letter}</h2><span className="ornament">✧</span><div className="letter-lines">{w.copy.introduction.map(line=><p key={line}>{line}</p>)}</div><p className="signature">{coupleNames}</p><p className="small-label">诚挚邀请 · 与我们同行</p></section>
    <section className="reflections-section section" id="reflections"><div className="reflections-copy reveal"><p className="eyebrow">02 / NOTES ON THE JOURNEY</p><h2>{w.copy.sections.reflections}</h2><p className="reflection-intro">在同一片天空下，向同一个远方。<br/>珍贵的记忆，会在往后的日子里慢慢显现。</p><div className="reflection-list">{w.reflections.map((item,i)=><article key={item.title}><span>0{i+1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
    <section className="calendar-section section" id="details"><div className="reveal"><p className="eyebrow">03 / SAVE OUR DATE</p><h2>{w.copy.sections.calendar}</h2><div className="date-card"><span>{month} · {w.date.slice(0,4)}</span><strong>{w.date.slice(8)}</strong><span>{weekday} · 户外相聚 · 晚宴</span><div className="date-card-bottom">{w.venue.city} · {w.venue.name}<span>{w.venue.address}</span></div></div><Countdown/>{w.dinnerTime&&<p className="muted">晚宴开席 · {w.dinnerTime}</p>}</div></section>
    <section className="journey-section section" id="journey"><div className="journey-heading reveal"><p className="eyebrow">04 / A DAY TO REMEMBER</p><h2>{w.copy.sections.journey}</h2><p className="muted">不必赶路，今天的目的地是相聚。</p></div><div className="journey-layout"><figure className="celebration-figure reveal"><img src={w.images.celebration} width={1536} height={1024} loading="lazy" alt="芙莉莲与辛美尔站在蓝白花园庆典的花拱门旁"/><figcaption>一场属于我们的户外庆典 <span>主题插画 · 非场地实景</span></figcaption></figure><div className="timeline">{events.length?events.map((event,i)=>{const Icon=icons[i%icons.length];return <article className="timeline-item reveal" key={event.id}><div className="timeline-icon"><Icon size={20}/></div><div>{event.time&&<span className="event-time">{event.time}</span>}<h3>{event.title}</h3><p>{event.description}</p></div><span className="event-number">0{i+1}</span></article>;}):<p className="muted">当日安排稍后更新</p>}</div></div><p className="journey-note"><Leaf size={15}/>{w.copy.outdoor}</p></section>
    <section className="ensemble-section section" id="companions"><div className="ensemble-heading reveal"><p className="eyebrow">05 / OUR DEAREST COMPANIONS</p><h2>{w.copy.sections.companions}</h2><p>在想象的旅途中，熟悉的伙伴也为这一天停下脚步。</p></div><figure className="ensemble-figure reveal"><img src={w.images.companions} width={1024} height={1536} loading="lazy" alt="旅伴们躺在蓝白花海中围成一圈"/></figure></section>
    <section className="venue-section section" id="venue"><div className="reveal"><p className="eyebrow">06 / FIND YOUR WAY</p><h2>{w.copy.sections.venue}</h2><div className="venue-card"><div className="venue-mark"><MapPin size={25}/><span>FUZHOU</span></div><h3>{w.venue.name}</h3><p className="venue-address">{w.venue.address}</p><div className="venue-actions"><a className="primary-link" href={navigationUrl} target="_blank" rel="noreferrer">打开地图导航 <ArrowUpRight size={16}/></a><CopyAddress/></div><p className="muted">导航将按完整地址搜索，请出发前核对目的地。</p>{[['交通提示',w.venue.traffic],['停车说明',w.venue.parking],['雨天安排',w.venue.rainPlan]].filter(([,v])=>v).map(([k,v])=><div className="venue-note" key={k}><b>{k}</b><p>{v}</p></div>)}{w.contact&&<div className="venue-note"><b>需要帮助？联系 {w.contact.name}</b><a href={'tel:'+w.contact.phone}>{w.contact.phone}</a></div>}</div></div></section>
    <section className="guest-guide section" id="guide"><div className="guide-heading reveal"><p className="eyebrow">07 / BEFORE YOU SET OUT</p><h2>{w.copy.sections.guide}</h2><p className="muted">把赴约前可能想知道的事，先写在这里。</p></div><div className="guide-grid">{w.guestGuide.map((item,i)=>{const Icon=[Clock3,Users,BedDouble][i%3];return <article className="guide-card reveal" key={item.question}><Icon size={21}/><span>0{i+1}</span><h3>{item.question}</h3><p>{item.answer}</p></article>})}</div></section>
    <section className="rsvp-section section" id="rsvp"><p className="eyebrow">08 / RSVP, WITH LOVE</p><h2>{w.copy.sections.rsvp}</h2><p className="rsvp-intro">席间的位置，留给珍贵的你。</p><figure className="rsvp-figure reveal"><img src="/images/guest-guide-river-blue.png" width={1536} height={1024} loading="lazy" alt="旅伴们坐在淡蓝河畔交谈"/></figure><RsvpForm/></section>
    <footer className="night-footer"><img src={w.images.night} width={1536} height={1024} loading="lazy" alt="芙莉莲与辛美尔坐在灯火旁仰望星空的原创插画"/><div className="night-copy"><p className="eyebrow">THE JOURNEY CONTINUES</p><span className="ornament">✧</span><h2>{w.copy.closing}</h2><p className="signature">{coupleNames}</p><p>{dateLabel} · {w.venue.city} · {w.venue.name}</p><a href="#top">回到旅程起点 <ArrowUp size={13}/></a></div></footer>
    <MusicToggle/><nav className="floating-nav" aria-label="婚礼快捷入口"><a href="#details">婚礼信息</a><a href="#rsvp">填写回执 <ArrowUpRight size={14}/></a></nav>
  </main>;
}
